color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.3193678294774145
  lightness: 0.2873726054094732
  saturation: 0.3468748163431883
  rhythmicContrast: 0.015218777814880013
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: hart
layout_spectrum: 0.27434688503853977
typography_spectrum: 0.4005223233252764
content: []
title: Traveler
description: I am desperate to walk on the road to get to your side.
github: true
author:
  name: Hart
  email: hartwar@sina.com
